// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | EducationSlice
  | ContactsSlice
  | CodeSamplesSlice
  | CertificationsSlice
  | AwardsSlice
  | ProjectsSlice
  | WorkSlice
  | AboutSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SettingsDocumentDataSlicesSlice = SettingsSlice;

/**
 * Item in *Settings → Repeatable Zone*
 */
export interface SettingsDocumentDataRepeatableZoneItem {
  /**
   * Label field in *Settings → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_zone[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * CTA Button field in *Settings → Repeatable Zone*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.repeatable_zone[].cta_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta_button: prismic.BooleanField;

  /**
   * Link field in *Settings → Repeatable Zone*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_zone[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Repeatable Zone field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_zone[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeatable_zone: prismic.GroupField<
    Simplify<SettingsDocumentDataRepeatableZoneItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *About → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Intro field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Link field in *About → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * AboutMe field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.aboutme
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  aboutme: prismic.KeyTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Awards → Default → Primary → Repeatable Zone*
 */
export interface AwardsSliceDefaultPrimaryRepeatableZoneItem {
  /**
   * Time field in *Awards → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.repeatable_zone[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Heading field in *Awards → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.repeatable_zone[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Awards → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.repeatable_zone[].body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;
}

/**
 * Primary content in *Awards → Default → Primary*
 */
export interface AwardsSliceDefaultPrimary {
  /**
   * Title field in *Awards → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Repeatable Zone field in *Awards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: awards.default.primary.repeatable_zone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeatable_zone: prismic.GroupField<
    Simplify<AwardsSliceDefaultPrimaryRepeatableZoneItem>
  >;
}

/**
 * Default variation for Awards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AwardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Awards*
 */
type AwardsSliceVariation = AwardsSliceDefault;

/**
 * Awards Shared Slice
 *
 * - **API ID**: `awards`
 * - **Description**: Awards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AwardsSlice = prismic.SharedSlice<"awards", AwardsSliceVariation>;

/**
 * Item in *Certifications → Default → Primary → Repeatable Zone*
 */
export interface CertificationsSliceDefaultPrimaryRepeatableZoneItem {
  /**
   * Time field in *Certifications → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.repeatable_zone[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Heading field in *Certifications → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.repeatable_zone[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Certifications → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.repeatable_zone[].body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;
}

/**
 * Primary content in *Certifications → Default → Primary*
 */
export interface CertificationsSliceDefaultPrimary {
  /**
   * Title field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Repeatable Zone field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.repeatable_zone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeatable_zone: prismic.GroupField<
    Simplify<CertificationsSliceDefaultPrimaryRepeatableZoneItem>
  >;
}

/**
 * Default variation for Certifications Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CertificationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CertificationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Certifications*
 */
type CertificationsSliceVariation = CertificationsSliceDefault;

/**
 * Certifications Shared Slice
 *
 * - **API ID**: `certifications`
 * - **Description**: Certifications
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CertificationsSlice = prismic.SharedSlice<
  "certifications",
  CertificationsSliceVariation
>;

/**
 * Item in *CodeSamples → Default → Primary → Repeatable Zone*
 */
export interface CodeSamplesSliceDefaultPrimaryRepeatableZoneItem {
  /**
   * Time field in *CodeSamples → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code_samples.default.primary.repeatable_zone[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Body field in *CodeSamples → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: code_samples.default.primary.repeatable_zone[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Heading field in *CodeSamples → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: code_samples.default.primary.repeatable_zone[].heading
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  heading: prismic.LinkField;
}

/**
 * Primary content in *CodeSamples → Default → Primary*
 */
export interface CodeSamplesSliceDefaultPrimary {
  /**
   * Title field in *CodeSamples → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: code_samples.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Repeatable Zone field in *CodeSamples → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: code_samples.default.primary.repeatable_zone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeatable_zone: prismic.GroupField<
    Simplify<CodeSamplesSliceDefaultPrimaryRepeatableZoneItem>
  >;
}

/**
 * Default variation for CodeSamples Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeSamplesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CodeSamplesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CodeSamples*
 */
type CodeSamplesSliceVariation = CodeSamplesSliceDefault;

/**
 * CodeSamples Shared Slice
 *
 * - **API ID**: `code_samples`
 * - **Description**: CodeSamples
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeSamplesSlice = prismic.SharedSlice<
  "code_samples",
  CodeSamplesSliceVariation
>;

/**
 * Item in *Contacts → Default → Primary → Repeable Zone*
 */
export interface ContactsSliceDefaultPrimaryRepeableZoneItem {
  /**
   * Link field in *Contacts → Default → Primary → Repeable Zone*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.repeable_zone[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * ContactName field in *Contacts → Default → Primary → Repeable Zone*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.repeable_zone[].contactname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contactname: prismic.TitleField;
}

/**
 * Primary content in *Contacts → Default → Primary*
 */
export interface ContactsSliceDefaultPrimary {
  /**
   * Title field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Repeable Zone field in *Contacts → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contacts.default.primary.repeable_zone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeable_zone: prismic.GroupField<
    Simplify<ContactsSliceDefaultPrimaryRepeableZoneItem>
  >;
}

/**
 * Default variation for Contacts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contacts*
 */
type ContactsSliceVariation = ContactsSliceDefault;

/**
 * Contacts Shared Slice
 *
 * - **API ID**: `contacts`
 * - **Description**: Contacts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactsSlice = prismic.SharedSlice<
  "contacts",
  ContactsSliceVariation
>;

/**
 * Item in *Education → Default → Primary → Repeatable Zone*
 */
export interface EducationSliceDefaultPrimaryRepeatableZoneItem {
  /**
   * Heading field in *Education → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.repeatable_zone[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Time field in *Education → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.repeatable_zone[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Body field in *Education → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.repeatable_zone[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Education → Default → Primary*
 */
export interface EducationSliceDefaultPrimary {
  /**
   * Title field in *Education → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Repeatable Zone field in *Education → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: education.default.primary.repeatable_zone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeatable_zone: prismic.GroupField<
    Simplify<EducationSliceDefaultPrimaryRepeatableZoneItem>
  >;
}

/**
 * Default variation for Education Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EducationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EducationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Education*
 */
type EducationSliceVariation = EducationSliceDefault;

/**
 * Education Shared Slice
 *
 * - **API ID**: `education`
 * - **Description**: Education
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EducationSlice = prismic.SharedSlice<
  "education",
  EducationSliceVariation
>;

/**
 * Item in *Projects → Default → Primary → Repeatable Zone*
 */
export interface ProjectsSliceDefaultPrimaryRepeatableZoneItem {
  /**
   * Time field in *Projects → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.repeatable_zone[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Image field in *Projects → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.repeatable_zone[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Projects → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.repeatable_zone[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Projects → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.repeatable_zone[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Title field in *Projects → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Repeatable Zone field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.repeatable_zone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeatable_zone: prismic.GroupField<
    Simplify<ProjectsSliceDefaultPrimaryRepeatableZoneItem>
  >;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Item in *Settings → Default → Primary → Repeatable Zone*
 */
export interface SettingsSliceDefaultPrimaryRepeatableZoneItem {
  /**
   * Label field in *Settings → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.default.primary.repeatable_zone[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * CTA Button field in *Settings → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.default.primary.repeatable_zone[].cta_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  cta_button: prismic.BooleanField;

  /**
   * Link field in *Settings → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.default.primary.repeatable_zone[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Primary content in *Settings → Default → Primary*
 */
export interface SettingsSliceDefaultPrimary {
  /**
   * Slice Title field in *Settings → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.default.primary.slice_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slice_title: prismic.KeyTextField;

  /**
   * Some Cool Site field in *Settings → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.default.primary.some_cool_site
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  some_cool_site: prismic.KeyTextField;

  /**
   * Fallback OG Image field in *Settings → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.default.primary.fallback_og_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Repeatable Zone field in *Settings → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.default.primary.repeatable_zone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeatable_zone: prismic.GroupField<
    Simplify<SettingsSliceDefaultPrimaryRepeatableZoneItem>
  >;
}

/**
 * Default variation for Settings Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SettingsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SettingsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Settings*
 */
type SettingsSliceVariation = SettingsSliceDefault;

/**
 * Settings Shared Slice
 *
 * - **API ID**: `settings`
 * - **Description**: Settings
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SettingsSlice = prismic.SharedSlice<
  "settings",
  SettingsSliceVariation
>;

/**
 * Item in *Work → Default → Primary → Repeatable Zone*
 */
export interface WorkSliceDefaultPrimaryRepeatableZoneItem {
  /**
   * Time field in *Work → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.repeatable_zone[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Heading field in *Work → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.repeatable_zone[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Work → Default → Primary → Repeatable Zone*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.repeatable_zone[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Work → Default → Primary*
 */
export interface WorkSliceDefaultPrimary {
  /**
   * Title field in *Work → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Repeatable Zone field in *Work → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.default.primary.repeatable_zone[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  repeatable_zone: prismic.GroupField<
    Simplify<WorkSliceDefaultPrimaryRepeatableZoneItem>
  >;
}

/**
 * Default variation for Work Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Work*
 */
type WorkSliceVariation = WorkSliceDefault;

/**
 * Work Shared Slice
 *
 * - **API ID**: `work`
 * - **Description**: Work
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSlice = prismic.SharedSlice<"work", WorkSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      SettingsDocumentDataRepeatableZoneItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      AwardsSlice,
      AwardsSliceDefaultPrimaryRepeatableZoneItem,
      AwardsSliceDefaultPrimary,
      AwardsSliceVariation,
      AwardsSliceDefault,
      CertificationsSlice,
      CertificationsSliceDefaultPrimaryRepeatableZoneItem,
      CertificationsSliceDefaultPrimary,
      CertificationsSliceVariation,
      CertificationsSliceDefault,
      CodeSamplesSlice,
      CodeSamplesSliceDefaultPrimaryRepeatableZoneItem,
      CodeSamplesSliceDefaultPrimary,
      CodeSamplesSliceVariation,
      CodeSamplesSliceDefault,
      ContactsSlice,
      ContactsSliceDefaultPrimaryRepeableZoneItem,
      ContactsSliceDefaultPrimary,
      ContactsSliceVariation,
      ContactsSliceDefault,
      EducationSlice,
      EducationSliceDefaultPrimaryRepeatableZoneItem,
      EducationSliceDefaultPrimary,
      EducationSliceVariation,
      EducationSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimaryRepeatableZoneItem,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      SettingsSlice,
      SettingsSliceDefaultPrimaryRepeatableZoneItem,
      SettingsSliceDefaultPrimary,
      SettingsSliceVariation,
      SettingsSliceDefault,
      WorkSlice,
      WorkSliceDefaultPrimaryRepeatableZoneItem,
      WorkSliceDefaultPrimary,
      WorkSliceVariation,
      WorkSliceDefault,
    };
  }
}
