// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  awards: dynamic(() => import("./Awards")),
  certifications: dynamic(() => import("./Certifications")),
  code_samples: dynamic(() => import("./CodeSamples")),
  contacts: dynamic(() => import("./Contacts")),
  education: dynamic(() => import("./Education")),
  projects: dynamic(() => import("./Projects")),
  settings: dynamic(() => import("./Settings")),
  work: dynamic(() => import("./Work")),
};
